fields:
  mailerlite_api_key:
    type: text
    display: 'MailerLite API Key'
    width: 50
  forms_section:
    type: section
    display: Forms
    hide_when: noApiKey
  forms:
    type: grid
    display: ' '
    instructions: 'Add a row for each form you want to capture subscribers from'
    fields:
      form:
        type: form
        instructions: 'Select the form you wish to use'
        width: 50
        max_items: 1
      subscriber_group:
        type: suggest
        mode: MailerLite.SubscriberGroup
        display: 'Subscriber Group'
        instructions: 'Optional: Which group would you like subscribers to be added to?'
        width: 50
        max_items: 1
      name_field:
        type: tags
        display: 'Name Field'
        instructions: 'Defaults to `name`, if your form uses a different field name change it here'
        default: name
        width: 50
      email_field:
        type: tags
        display: 'Email Field'
        instructions: 'Defaults to `email`, if your form uses a different field name change it here'
        default: email
        width: 50
      auto_split_name:
        type: toggle
        display: 'Automatically Split Name'
        instructions: 'Split into `name` and `last_name` on <a href="https://app.mailerlite.com" target="_blank">MailerLite</a>, this setting is ignored if you map `last_name` seperately'
        default: true
        width: 100
      marketing_optin_field:
        type: tags
        display: 'Opt-in Field'
        instructions: 'Optional: This field should be an un-ticked checkbox that conforms to the GDPR Regulations'
        width: 50
        max_items: 1
      marketing_permissions_fields:
        type: tags
        display: 'Marketing Permissions Field'
        instructions: 'Optional: You will need to setup a `marketing_permissions` field on <a href="https://app.mailerlite.com" target="_blank">MailerLite</a>, for more info see <a href="https://help.mailerlite.com/article/show/88106-checkboxes-and-marketing-permissions" target="_blank">this article</a>'
        width: 50
      mapped_fields:
        type: grid
        display: 'Mapped Fields'
        instructions: 'Optional: You can map <a href="https://app.mailerlite.com" target="_blank">MailerLite</a> each Subscriber Field to Form Fields here'
        fields:
          subscriber_field:
            type: suggest
            mode: MailerLite.SubscriberFields
            display: 'Subscriber Field'
            width: 50
            max_items: 1
          mapped_form_fields:
            type: tags
            display: 'Form Field'
            width: 50
        mode: stacked
        add_row: Add Field
    mode: stacked
    min_rows: "1"
    hide_when: noApiKey
    add_row: Add Form
